Document: maeremote
Title: Debian maeremote Manual
Author: <insert document author here>
Abstract: This manual describes what maeremote is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/maeremote/maeremote.sgml.gz

Format: postscript
Files: /usr/share/doc/maeremote/maeremote.ps.gz

Format: text
Files: /usr/share/doc/maeremote/maeremote.text.gz

Format: HTML
Index: /usr/share/doc/maeremote/html/index.html
Files: /usr/share/doc/maeremote/html/*.html


